// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9khUWmozN1iqiiTyAwvqXU
// Component: 1Qw0dLE7-z
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: 9khUWmozN1iqiiTyAwvqXU/projectcss
import sty from "./PlasmicSidebarMenuItem.module.css"; // plasmic-import: 1Qw0dLE7-z/css

import WalletSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__WalletSvgrepoCom1Svg"; // plasmic-import: 4G1cCMeGFh/icon

export type PlasmicSidebarMenuItem__VariantMembers = {
  isActive: "isActive";
};

export type PlasmicSidebarMenuItem__VariantsArgs = {
  isActive?: SingleBooleanChoiceArg<"isActive">;
};

type VariantPropType = keyof PlasmicSidebarMenuItem__VariantsArgs;
export const PlasmicSidebarMenuItem__VariantProps = new Array<VariantPropType>(
  "isActive"
);

export type PlasmicSidebarMenuItem__ArgsType = {
  url?: string;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicSidebarMenuItem__ArgsType;
export const PlasmicSidebarMenuItem__ArgProps = new Array<ArgPropType>(
  "url",
  "children"
);

export type PlasmicSidebarMenuItem__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  freeBox?: p.Flex<"div">;
};

export interface DefaultSidebarMenuItemProps {
  url?: string;
  children?: React.ReactNode;
  isActive?: SingleBooleanChoiceArg<"isActive">;
  className?: string;
}

function PlasmicSidebarMenuItem__RenderFunc(props: {
  variants: PlasmicSidebarMenuItem__VariantsArgs;
  args: PlasmicSidebarMenuItem__ArgsType;
  overrides: PlasmicSidebarMenuItem__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootisActive]: hasVariant(variants, "isActive", "isActive") }
      )}
    >
      <p.Stack
        as={p.PlasmicLink}
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        hasGap={true}
        className={classNames(projectcss.all, projectcss.a, sty.link, {
          [sty.linkisActive]: hasVariant(variants, "isActive", "isActive")
        })}
        component={Link}
        href={args.url}
        platform={"nextjs"}
      >
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox, {
              [sty.freeBoxisActive]: hasVariant(
                variants,
                "isActive",
                "isActive"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <WalletSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__fWx4)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xErYq
                    )}
                  >
                    {"Menu Item"}
                  </div>
                </React.Fragment>
              ),
              value: args.children,
              className: classNames(sty.slotTargetChildren, {
                [sty.slotTargetChildrenisActive]: hasVariant(
                  variants,
                  "isActive",
                  "isActive"
                )
              })
            })}
          </p.Stack>
        ) : null}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link", "freeBox"],
  link: ["link", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSidebarMenuItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSidebarMenuItem__VariantsArgs;
    args?: PlasmicSidebarMenuItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSidebarMenuItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSidebarMenuItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSidebarMenuItem__ArgProps,
          internalVariantPropNames: PlasmicSidebarMenuItem__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSidebarMenuItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSidebarMenuItem";
  } else {
    func.displayName = `PlasmicSidebarMenuItem.${nodeName}`;
  }
  return func;
}

export const PlasmicSidebarMenuItem = Object.assign(
  // Top-level PlasmicSidebarMenuItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicSidebarMenuItem
    internalVariantProps: PlasmicSidebarMenuItem__VariantProps,
    internalArgProps: PlasmicSidebarMenuItem__ArgProps
  }
);

export default PlasmicSidebarMenuItem;
/* prettier-ignore-end */
